# Generated by Django 2.0.2 on 2018-02-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReferenceId', models.CharField(max_length=30)),
                ('Sender', models.CharField(max_length=30)),
                ('Reciever', models.CharField(max_length=30)),
            ],
        ),
    ]
