# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newform',
            name='GoodsDescription',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newform',
            name='SenderName',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='Status',
            field=models.TextField(max_length=5000),
        ),
    ]
