# Generated by Django 2.0.2 on 2018-02-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=30)),
                ('SenderAddress', models.CharField(max_length=30)),
                ('RecieverName', models.CharField(max_length=30)),
                ('RecieverAddress', models.CharField(max_length=30)),
                ('referenceID', models.CharField(max_length=30)),
                ('GoodsareFrom', models.CharField(max_length=30)),
                ('GoodsTo', models.CharField(max_length=30)),
                ('DepatureDate', models.CharField(max_length=30)),
                ('Depaturetime', models.CharField(max_length=30)),
                ('ArrivalDate', models.CharField(max_length=30)),
                ('ArrivalTime', models.CharField(max_length=30)),
                ('GoodsDescription', models.TextField(max_length=50)),
                ('Status', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trackforms',
            name='newform',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='scoty.NewForm'),
        ),
    ]
