# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoty', '0002_auto_20180524_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newform',
            name='ArrivalDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='ArrivalTime',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='DepatureDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='Depaturetime',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='GoodsTo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='GoodsareFrom',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='RecieverAddress',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='RecieverName',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='SenderAddress',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newform',
            name='referenceID',
            field=models.CharField(max_length=250),
        ),
    ]
