# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoty', '0003_auto_20180524_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackforms',
            name='Reciever',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trackforms',
            name='ReferenceId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trackforms',
            name='Sender',
            field=models.CharField(max_length=250),
        ),
    ]
